version: '3'
services:
  angular-app:
    build:
      context: ./src/Web/ClientApp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5000:80"