USE railway;

CREATE TABLE Users (
	Id NVARCHAR(50) PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(80) NOT NULL,
    AvatarURL NVARCHAR(100) NOT NULL,
    Bio NVARCHAR(500) NOT NULL
);

CREATE TABLE Kudos (
	Id INT AUTO_INCREMENT PRIMARY KEY,
    SenderId NVARCHAR(50),
    ReceiverId NVARCHAR(50) NOT NULL,
    Title NVARCHAR(50) NOT NULL,
    Message NVARCHAR(200) NOT NULL,
    TeamPlayer BIT NOT NULL,
    OneOfAKind BIT NOT NULL,
    Creative BIT NOT NULL,
    HighEnergy BIT NOT NULL,
    Awesome BIT NOT NULL,
    Achiever BIT NOT NULL,
    Sweetness BIT NOT NULL,
    TheDate DATE NOT NULL
);

CREATE TABLE Comments (
	Id INT AUTO_INCREMENT PRIMARY KEY,
    KudoId INT NOT NULL,
    SenderId NVARCHAR(50) NOT NULL,
    Message NVARCHAR(200) NOT NULL
);